# Generated by Django 2.0.2 on 2018-09-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
